-- Lightweight, privacy-respecting funnel instrumentation for the current
-- sales-assisted funnel (Job Assistant -> pricing -> contact form ->
-- manually onboarded company). See FUNNEL_TRACKING.md for the full design
-- rationale (why a first-party table instead of relying on Vercel
-- Analytics alone: this needs to be queryable for a real admin dashboard
-- with date-range filtering, and joined against `company`/
-- `contact_submissions`, neither of which Vercel Analytics' custom events
-- support - Vercel Analytics events are added alongside this as a free
-- secondary signal, not the source of truth).
--
-- No PII, no CV/interview content: an anonymous, client-generated
-- session_id only. The contact form's own submission (name/email/company)
-- already lives in contact_submissions - this table is not a copy of that,
-- just a record that a submission happened, from where.

CREATE TABLE IF NOT EXISTS "public"."funnel_events" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "event_type" text NOT NULL,
    "session_id" text NOT NULL,
    "source" text,
    "plan" text,
    "metadata" jsonb,
    CONSTRAINT "funnel_events_event_type_check" CHECK (
        event_type IN (
            'job_assistant_started',
            'job_assistant_completed',
            'pricing_viewed',
            'pricing_cta_clicked',
            'contact_form_submitted',
            'roi_calculator_used'
        )
    ),
    CONSTRAINT "funnel_events_source_check" CHECK (
        source IS NULL OR source IN ('homepage', 'pricing_page', 'marketing_site')
    ),
    CONSTRAINT "funnel_events_plan_check" CHECK (
        plan IS NULL OR plan IN ('free', 'momentum', 'infinity')
    )
);

CREATE INDEX IF NOT EXISTS "idx_funnel_events_type_created" ON "public"."funnel_events" ("event_type", "created_at");
CREATE INDEX IF NOT EXISTS "idx_funnel_events_session" ON "public"."funnel_events" ("session_id");

ALTER TABLE "public"."funnel_events" ENABLE ROW LEVEL SECURITY;

-- Anyone (including fully anonymous visitors on either property) can log a
-- funnel event - that's the entire point of top-of-funnel instrumentation.
-- Same pattern already used for happiness_sessions ("Allow anonymous
-- session creation"). Not a sensitive-data table like medical_certificates/
-- openedpositions were - this is intentionally public write-only telemetry
-- with no way to read back what anyone else logged.
CREATE POLICY "Anyone can log a funnel event"
ON "public"."funnel_events" FOR INSERT
TO public
WITH CHECK (true);

-- Only super admins can read funnel data (matches the existing
-- "Super admins can view all tickets" pattern - company slug innohr/hrinno).
CREATE POLICY "Super admins can view funnel events"
ON "public"."funnel_events" FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM "public"."users" u
    WHERE u.id = auth.uid() AND u.is_super_admin = true
  )
);

REVOKE UPDATE, DELETE ON TABLE "public"."funnel_events" FROM "anon", "authenticated";
GRANT INSERT ON TABLE "public"."funnel_events" TO "anon", "authenticated";
GRANT SELECT ON TABLE "public"."funnel_events" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."funnel_events_id_seq" TO "anon", "authenticated";

-- Closes the loop on "manually onboarded paying company" being an
-- off-platform step today: a nullable, admin-set reference from a company
-- to the contact_submissions row (if any) that led to it. Not populated
-- automatically - see FUNNEL_TRACKING.md for how to set it.
ALTER TABLE "public"."company"
  ADD COLUMN IF NOT EXISTS "onboarded_from_contact_submission_id" uuid REFERENCES "public"."contact_submissions"("id");
