-- Runtime-adjustable data retention settings for medical certificates and
-- CV data, plus an audit trail of who changed them and when, and a log of
-- what's actually been deleted (scheduled or manual).
--
-- IMPORTANT: retention_days values seeded below (365) are PLACEHOLDERS, not
-- a legal or compliance determination. See REDACTION_RETENTION_FIX.md for
-- the explicit list of decisions that need real legal input before these
-- numbers should be trusted. This migration does not make HRInno GDPR or
-- HIPAA compliant — it only makes the retention period something a
-- non-engineer can correct once a real number is decided, instead of
-- something requiring a code change and redeploy.

create table if not exists public.data_retention_settings (
  id bigint generated by default as identity primary key,
  data_type text not null unique check (
    data_type in ('medical_certificate', 'cv_job_assistant', 'cv_company_pipeline')
  ),
  -- NULL = retain indefinitely, no automatic deletion for this data type.
  retention_days integer check (retention_days is null or retention_days > 0),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.users(id)
);

comment on table public.data_retention_settings is
  'Legal/compliance-editable retention periods per data type. Read fresh by the retention sweep on every run — never cached at deploy time. retention_days placeholders require real legal review; see REDACTION_RETENTION_FIX.md.';

-- Full history of changes to the above, so "who changed it and when" isn't
-- limited to only the most recent edit.
create table if not exists public.data_retention_settings_history (
  id bigint generated by default as identity primary key,
  data_type text not null,
  old_retention_days integer,
  new_retention_days integer,
  changed_at timestamptz not null default now(),
  changed_by uuid references public.users(id)
);

comment on table public.data_retention_settings_history is
  'Append-only audit log of every change to data_retention_settings, for the admin UI audit trail.';

-- Log of every actual deletion performed by the retention sweep or a manual
-- admin "delete now" action, so what was deleted and when stays visible
-- after the underlying record is gone.
create table if not exists public.data_deletion_log (
  id bigint generated by default as identity primary key,
  data_type text not null,
  record_id text not null,
  storage_path text,
  reason text not null check (reason in ('scheduled', 'manual')),
  deleted_by uuid references public.users(id),
  deleted_at timestamptz not null default now(),
  record_created_at timestamptz
);

comment on table public.data_deletion_log is
  'Audit trail of records actually deleted by the retention sweep (reason=scheduled) or an admin (reason=manual). record_id is stored as text since candidats/medical_certificates use bigint ids.';

-- All access goes through service-role-backed admin API routes (matching
-- the existing pattern for funnel_events / contact-submissions), which do
-- their own super-admin check. No anon/authenticated grants.
alter table public.data_retention_settings enable row level security;
alter table public.data_retention_settings_history enable row level security;
alter table public.data_deletion_log enable row level security;

revoke all on public.data_retention_settings from anon, authenticated;
revoke all on public.data_retention_settings_history from anon, authenticated;
revoke all on public.data_deletion_log from anon, authenticated;

-- Seed placeholder rows so the settings table is never empty. 365 days is
-- an arbitrary placeholder, not a researched or legally-informed default —
-- see the "requires human/legal decision" list in REDACTION_RETENTION_FIX.md.
insert into public.data_retention_settings (data_type, retention_days, updated_by)
values
  ('medical_certificate', 365, null),
  ('cv_job_assistant', 365, null),
  ('cv_company_pipeline', 365, null)
on conflict (data_type) do nothing;
